/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hpgame;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author borodin
 */
public class GameUI extends javax.swing.JFrame
{

	private List<QandA> qas;
	private int ansver;
	private int btnansver;
	private Timer tsg = null;
	private Timer teg = null;

	/**
	 * Creates new form GameUI
	 */
	public GameUI(List<QandA> qs)
	{
		this.qas = qs;
		// this.setExtendedState(JFrame.MAXIMIZED_BOTH);
		initComponents();
		getContentPane().setBackground(new Color(0,153,204));  //Whatever color

		jButton5.setMinimumSize(new Dimension(300, 55));
		jButton1.setVisible(false);
		jButton2.setVisible(false);
		jButton3.setVisible(false);
		jButton4.setVisible(false);
		setVisible(true);
		// TODO that should not work !!!
		// I setinf label (for photo) too big entire seze of the windo.
		// int H = (int) this.getContentPane().getSize().getHeight() - 280;
		// int W = (int) this.getContentPane().getSize().getWidth();
		// Utilitis.print("frame h - " + H +"  frtame w - " + W);
		// jLabel_photo.setPreferredSize(new Dimension(W, H));
	}

	private void startGame()
	{
		if (tsg != null) tsg.stop();
		// teg = new Timer(6000, new ActionListener()
		int deleyx = 1000 * 60 * 60 * 1; // 1 hour
		teg = new Timer(deleyx, new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				// just restart gave if no one guesses corectly
				startGame();
			}
		});
		teg.setRepeats(false);
		teg.start();

		// starting the game 
		jButton5.setVisible(false);
		jButton1.setVisible(true);
		jButton2.setVisible(true);
		jButton3.setVisible(true);
		jButton4.setVisible(true);

		Random generator = new Random();
		int i = generator.nextInt(qas.size());
		addPhoto(qas.get(i).Q.getAbsolutePath(), i);
	}
	private void finishGame()
	{
		if (teg != null ) teg.stop();
		// strrting game after 5 seconds if no one pushe the buttone.
		tsg = new Timer (5000, new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				startGame();
			}
		});

		 tsg.setRepeats(false);
		 tsg.start();
		
		jButton5.setVisible(true);
		jButton1.setVisible(false);
		jButton2.setVisible(false);
		jButton3.setVisible(false);
		jButton4.setVisible(false);

		// Random generator = new Random();
		// int i = generator.nextInt(qas.size());
		// addPhoto(qas.get(i).Q.getAbsolutePath(), i);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel_title = new javax.swing.JLabel();
        jLabel_photo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 204));
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel_title.setFont(new java.awt.Font("HPFutura Light", 2, 24)); // NOI18N
        jLabel_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_title.setText("Guess Who on Photo");
        getContentPane().add(jLabel_title, new java.awt.GridBagConstraints());

        jLabel_photo.setBackground(new java.awt.Color(0, 153, 255));
        jLabel_photo.setForeground(new java.awt.Color(51, 153, 255));
        jLabel_photo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_photo.setBorder(new javax.swing.border.MatteBorder(null));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jLabel_photo, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        jButton5.setBackground(new java.awt.Color(0, 0, 255));
        jButton5.setFont(new java.awt.Font("HP Simplified Light", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(204, 255, 0));
        jButton5.setText("Start");
        jButton5.setMaximumSize(new java.awt.Dimension(4000, 1000));
        jButton5.setMinimumSize(new java.awt.Dimension(500, 255));
        jButton5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 255));
        jButton3.setFont(new java.awt.Font("HP Simplified Light", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 51));
        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 255));
        jButton4.setFont(new java.awt.Font("HP Simplified Light", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 51));
        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 255));
        jButton2.setFont(new java.awt.Font("HP Simplified Light", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 51));
        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("HP Simplified Light", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 51));
        jButton1.setText("jButton1");
        jButton1.setFocusTraversalPolicyProvider(true);
        jButton1.setMaximumSize(new java.awt.Dimension(299, 137));
        jButton1.setMinimumSize(new java.awt.Dimension(200, 55));
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 622, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1))
            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        Utilitis.print("Buttone 1 is presed");
        if (btnansver == 1)
        {
            Utilitis.print("The andsver is: " + btnansver);
            setAnsvPoto(qas.get(ansver).A);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        Utilitis.print("Buttone 2 is presed");
        if (btnansver == 2)
        {
            Utilitis.print("The andsver is: " + btnansver);
            setAnsvPoto(qas.get(ansver).A);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        Utilitis.print("Buttone 4 is presed");
        if (btnansver == 4)
        {
            Utilitis.print("The andsver is: " + btnansver);
            setAnsvPoto(qas.get(ansver).A);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        Utilitis.print("Buttone 3 is presed");
        if (btnansver == 3)
        {
            Utilitis.print("The andsver is: " + btnansver);
            setAnsvPoto(qas.get(ansver).A);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton5ActionPerformed
    {//GEN-HEADEREND:event_jButton5ActionPerformed
        startGame();
    }//GEN-LAST:event_jButton5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_photo;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

	///////////////////////////////////////////////////////////////////////
	private void addPhoto(String photo, int x)
	{
		int height = (int) (Toolkit.getDefaultToolkit().getScreenSize().height*0.8);
		int width  = (int) (Toolkit.getDefaultToolkit().getScreenSize().width *0.8);
		jLabel_photo.setText("");
		Utilitis.print("Aditing photo at the begining of the game:");
		Utilitis.print("H = " + height + " W = " + width);

		ansver = x;
		Random generator = new Random();
		btnansver = generator.nextInt(4) + 1;
		setButtons();
		Utilitis.print(photo);
		BufferedImage imge = null;
		try
		{
			imge = ImageIO.read(qas.get(ansver).Q);
			Image dimg = Utilitis.scaleImage(imge, BufferedImage.TYPE_INT_RGB, width, height);
			ImageIcon icon = new ImageIcon(dimg);
			jLabel_photo.setIcon(icon);

		} catch (Exception e)
		{
			Utilitis.print(e.getLocalizedMessage());
		}
	}

	private void setAnsvPoto(File f)
	{
		int height = (int) (Toolkit.getDefaultToolkit().getScreenSize().height*0.8);
		int width  = (int) (Toolkit.getDefaultToolkit().getScreenSize().width *0.8);
		Utilitis.print("H = " + height + " W = " + width);
	
		BufferedImage imge = null;
		try
		{
			imge = ImageIO.read(qas.get(ansver).A);
			Image dimg = Utilitis.scaleImage(imge, BufferedImage.TYPE_INT_RGB, width, height);
			// Image dimg = imge.getScaledInstance((int) (width), (int) (height), Image.SCALE_SMOOTH);
			ImageIcon icon = new ImageIcon(dimg);
			jLabel_photo.setIcon(icon);
			
		} catch (Exception e)
		{
			Utilitis.print(e.getLocalizedMessage());
		}
		if (f != null)
			jLabel_photo.setText("");
		 else
			jLabel_photo.setText("You are right!");

		finishGame();
	}

	private void setButtons()
	{
		String a = Utilitis.getFilename(qas.get(ansver).Q);
		Utilitis.print("Amensver is : " + btnansver + " - " + a);

		List<String> restAs = new ArrayList<String>();

		for (int i=0; i<qas.size(); i++)
		{
			String k = Utilitis.getFilename(qas.get(i).Q);
			if (i != ansver ) restAs.add(k);
		}
		for (int j=1; j<=4; j++)
		{
			if( j != btnansver)
			{
				Random generator = new Random();
				int x = generator.nextInt(restAs.size());
				setNameForButton(j, restAs.get(x));
				restAs.remove(x);
			}
		}

		setNameForButton(btnansver, a);
	}

	private void setNameForButton(int x, String name)
	{
		switch (x)
		{
			case 1:
				jButton1.setText(name);
				break;
			case 2:
				jButton2.setText(name);
				break;
			case 3:
				jButton3.setText(name);
				break;
			case 4:
				jButton4.setText(name);
				break;
		}
	}

}
